name: CI

env:
  SDK_BRANCH_NAME: ${{ inputs.sdk_branch  || github.head_ref || github.ref_name || 'main' }}
  TEST_DATA_BRANCH_NAME: ${{ inputs.test_data_branch || 'main' }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

  workflow_call:
    inputs:
      test_data_branch:
        type: string
        description: The branch in sdk-test-data to target for testcase files
        required: false
        default: main
      sdk_branch:
        type: string
        description: The branch of the SDK to test
        required: false
      
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: Eppo-exp/react-native-sdk
          ref: ${{ env.SDK_BRANCH_NAME}}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint files
        run: yarn lint

      - name: Typecheck files
        run: yarn typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: Eppo-exp/react-native-sdk
          ref: ${{ env.SDK_BRANCH_NAME}}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install dependencies
        run: yarn install

      - name: Run unit tests
        run: make test branchName=${{env.TEST_DATA_BRANCH_NAME}}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: Eppo-exp/react-native-sdk
          ref: ${{ env.SDK_BRANCH_NAME}}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build package
        run: yarn prepack
